# Generated by Django 4.2.16 on 2024-09-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_email_patient_gender_alter_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='outdoor', max_length=7),
        ),
    ]
