# Generated by Django 4.2.16 on 2024-10-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_patient_admission_date_patient_discharge_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='bed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_patient', to='hospital.bed'),
        ),
    ]
