# Generated by Django 4.2.16 on 2024-10-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_remove_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='company',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
