# Generated by Django 4.2.16 on 2024-10-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_medication_action_medication_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_call', 'On Call'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
