# Generated by Django 4.2.16 on 2024-10-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_ambulance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ambulance_photos/'),
        ),
    ]
