# Generated by Django 4.2.16 on 2024-10-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_ambulanceassignment_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulanceassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=20),
        ),
    ]
